import { useState } from 'react'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell">
      <header className="site-header"><a className="wordmark" href="#top" onClick={closeMenu} aria-label="ORCA home"><span className="wordmark-mark">O</span><span>ORCA</span></a><button className="menu-toggle" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation"><span></span><span></span></button><nav className={menuOpen ? 'site-nav is-open' : 'site-nav'} aria-label="Main navigation"><a href="#mission" onClick={closeMenu}>Our mission</a><a href="#intelligence" onClick={closeMenu}>Intelligence</a><a href="#field-notes" onClick={closeMenu}>Field notes</a></nav><a className="header-cta" href="#field-notes">Read the report <span>↗</span></a></header>
      <main id="top">
        <section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="live-dot"></span> A field guide for the open water</p><h1>Know the water.<br /><em>Trust the journey.</em></h1><p className="hero-lede">ORCA brings weather, navigation and the living ocean into one calm, clear view, so every trip starts with a better question: is it safe to go?</p><a className="primary-button" href="#intelligence">Explore ORCA <span>↓</span></a></div><div className="hero-visual" aria-label="Illustration of an ocean swell and navigation route"><div className="coordinate-label">09° 58' N<br />76° 16' E</div><div className="sun-disc"></div><div className="route-line"></div><div className="route-point point-one"></div><div className="route-point point-two"></div><div className="wave wave-back"></div><div className="wave wave-mid"></div><div className="wave wave-front"></div><p className="visual-caption">The sea is never still.<br /><strong>Neither should your awareness be.</strong></p></div><div className="hero-stamp">EST.<br /><strong>2024</strong></div></section>
        <section className="signal-bar" aria-label="Current ocean signal"><span className="signal-label">Current signal</span><span className="signal-status"><i></i> Conditions are favorable</span><span className="signal-location">Arabian Sea · 09:42 UTC</span><span className="signal-arrow">→</span></section>
        <section className="manifesto-section" id="mission"><div className="section-kicker">01 / Why ORCA exists</div><div className="manifesto-content"><h2>The ocean gives.<br /><em>We listen back.</em></h2><div><p>For generations, fishermen and sailors have read the wind, watched the clouds, and learned the water by heart. Today, the ocean is changing faster than any one person can track.</p><p>ORCA gathers the signals around you and turns them into something human: a clearer decision, a safer route, a better day at sea.</p></div></div></section>
        <section className="intelligence-section" id="intelligence"><div className="section-heading"><div className="section-kicker">02 / One view of the water</div><h2>Everything you need.<br /><em>Nothing in the way.</em></h2></div><div className="feature-grid"><article className="feature-card feature-main"><span className="feature-number">01</span><div className="weather-icon">☼</div><h3>Weather<br />in context</h3><p>Wind, rainfall, temperature and wave conditions become a single, readable picture.</p><a href="#field-notes">See the forecast <span>↗</span></a></article><article className="feature-card feature-coral"><span className="feature-number">02</span><div className="feature-symbol">⌁</div><h3>Find where<br />life gathers</h3><p>AI maps likely fishing zones using satellite data, biodiversity and community knowledge.</p><a href="#field-notes">Follow the signal <span>↗</span></a></article><article className="feature-card feature-dark"><span className="feature-number">03</span><div className="feature-symbol">◉</div><h3>Move with<br />confidence</h3><p>Navigation that keeps your course clear and territorial boundaries visible.</p><a href="#field-notes">Trace a route <span>↗</span></a></article></div></section>
        <section className="offline-section"><div className="offline-graphic"><span className="orbit orbit-one"></span><span className="orbit orbit-two"></span><span className="offline-core">O</span></div><div><div className="section-kicker">03 / Intelligence that travels</div><h2>When the signal<br /><em>goes quiet.</em></h2><p>ORCA is built for the moments when the horizon is bigger than your connection. Our cloud + local hybrid architecture keeps your maps, your track and the essential picture with you, online or off.</p><span className="offline-note">LOCAL MODE / READY TO DEPART</span></div></section>
        <section className="field-notes-section" id="field-notes"><div className="field-notes-head"><div><div className="section-kicker">04 / From the logbook</div><h2>Notes from<br /><em>the blue.</em></h2></div><a className="text-link" href="#top">View all notes <span>↗</span></a></div><div className="notes-grid"><article className="note-card"><div className="note-image note-image-one"><span>MONSOON<br />WATCH</span></div><p className="note-meta">02.08.24 · WEATHER</p><h3>Reading the rain before it arrives</h3><a href="#top">Read note <span>↗</span></a></article><article className="note-card"><div className="note-image note-image-two"><span>THE<br />BOUNDARY</span></div><p className="note-meta">18.07.24 · NAVIGATION</p><h3>Lines on a map, safety on the water</h3><a href="#top">Read note <span>↗</span></a></article><article className="note-card"><div className="note-image note-image-three"><span>FOLLOW<br />THE LIFE</span></div><p className="note-meta">04.07.24 · OCEAN LIFE</p><h3>How satellites help us find the fish</h3><a href="#top">Read note <span>↗</span></a></article></div></section>
        <section className="closing-section"><p className="eyebrow"><span className="live-dot"></span> For everyone who makes a living on the water</p><h2>Go further.<br /><em>Come home safer.</em></h2><a className="primary-button" href="#top">Begin with ORCA <span>↗</span></a></section>
      </main><footer className="site-footer"><a className="wordmark" href="#top"><span className="wordmark-mark">O</span><span>ORCA</span></a><p>Built for the people who live by the water.</p><p>© 2024 ORCA / Open water intelligence</p></footer>
    </div>
  )
}

export default App
